## Merge and Split

In the previous notebook we have simulated 400k samples for each bin, the purpose of this notebook is to merge all the samples, shuffle them and split them into Train, Test and Val datasets.

## Used functions

In [1]:
import pandas as pd
import numpy as np
import h5py
import os

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Load each dataset

In [3]:
d1 = pd.read_parquet('/content/drive/MyDrive/AzONet_New_145/notebooks/3_data_simulation/NewDataAzONetV2/bin_0.parquet')

In [4]:
d2 = pd.read_parquet('/content/drive/MyDrive/AzONet_New_145/notebooks/3_data_simulation/NewDataAzONetV2/bin_1.parquet')

In [5]:
d3 = pd.read_parquet('/content/drive/MyDrive/AzONet_New_145/notebooks/3_data_simulation/NewDataAzONetV2/bin_2.parquet')

In [6]:
d4 = pd.read_parquet('/content/drive/MyDrive/AzONet_New_145/notebooks/3_data_simulation/NewDataAzONetV2/bin_3.parquet')

In [7]:
d5 = pd.read_parquet('/content/drive/MyDrive/AzONet_New_145/notebooks/3_data_simulation/NewDataAzONetV2/bin_4.parquet')

In [8]:
d5.head()

,Espectro,Espesor,R1,R2,Sellmeier,Absorcion,ne
0,"[1.3457722212978553e-306, 1.2085007945729858e-...",1427.977644,34.294072,17.753767,"[3.2526443528904183, 1557541.7655233573, 11383...","[0.011490285766159673, 9.830317810066706, 351....",1.798137e+26
1,"[1.8037227206199377e-306, 1.6068994431658612e-...",1397.289447,38.548901,17.411677,"[3.2402379559019456, 1682420.7803791869, 30664...","[0.0072014393588117915, 9.326651427269072, 348...",1.272962e+26
2,"[1.7145177358449947e-306, 1.52886425504478e-30...",1150.582607,44.532590,14.819425,"[3.397875750284605, 2334355.2282904326, 262539...","[0.002285086143016024, 8.727649747834823, 352....",1.323828e+26
3,"[1.6186217686539172e-306, 1.4437890587667563e-...",1392.076374,50.433893,15.016192,"[3.244246735068651, 2244646.736470936, 2085680...","[0.008543617144330152, 9.6940828646061, 356.88...",1.945091e+26
4,"[1.808245011965726e-306, 1.6108509806852154e-3...",1180.905499,25.392177,30.157995,"[3.3958960078541267, 1258670.7137032908, 27616...","[0.01047312850020734, 9.105137208342432, 351.4...",1.548740e+26

In [9]:
df_final = pd.concat([d1, d2, d3, d4, d5], ignore_index=True)

In [10]:
df_final.shape

(1200000, 7)

In [11]:
df_final = df_final.sample(frac=1).reset_index(drop=True)

In [12]:
df_final.head(15)

,Espectro,Espesor,R1,R2,Sellmeier,Absorcion,ne
0,"[1.8535587862763908e-306, 1.6507321030792435e-...",1069.068059,28.998923,25.317687,"[3.249627870587824, 2291193.501798607, 2409965...","[0.0030031336423205525, 10.839857037275348, 36...",1.161924e+26
1,"[1.840232999008403e-306, 1.6387326094602257e-3...",814.232561,11.903297,36.501740,"[3.248716729515264, 1199089.8619998167, 252025...","[0.0036457519032666286, 9.647085614909214, 363...",2.518553e+26
2,"[1.382627759493285e-306, 1.2358807726900032e-3...",398.963831,7.849488,47.351551,"[4.282410133930843, 98338.85746759964, 5987654...","[0.01057609068300517, 12.856247952141734, 362....",9.151767e+25
3,"[2.0355385980313498e-306, 1.809843963718537e-3...",348.045794,15.480403,6.344644,"[3.279033504813903, 1545943.8809780658, 128171...","[0.008310190429281399, 10.026019577615353, 356...",2.340254e+26
4,"[1.9947756989604956e-306, 1.7747398865880904e-...",413.575122,14.632233,16.700208,"[4.1822876670354425, 729772.7687962402, 103021...","[0.005638627402431647, 10.404746203617188, 357...",3.083444e+26
5,"[1.985635963580847e-306, 1.7662922837986795e-3...",407.326401,11.635042,12.406542,"[4.400234172355472, 308302.87692275376, 105091...","[0.0120110426859467, 12.54506367364414, 355.25...",4.450643e+26
6,"[1.816112834339129e-306, 1.617655565305491e-30...",813.571497,24.872375,31.471125,"[3.2635835556051003, 1478972.5999799033, 14344...","[0.010313754050736553, 9.40277951532309, 368.9...",3.145522e+26
7,"[1.6053244312864465e-306, 1.433529008891707e-3...",865.436560,12.077225,56.812133,"[3.2476920366105477, 1716792.0025152618, 24749...","[0.008836621898027783, 11.991610657474665, 366...",3.622233e+26
8,"[1.9451637408977786e-306, 1.730751572817465e-3...",1250.186858,27.062521,11.451124,"[3.248699762408116, 1114051.2177333566, 845813...","[0.010246758467774161, 10.495629471462209, 346...",1.100017e+26
9,"[1.9015178935765348e-306, 1.6930875086848956e-...",468.086306,42.563340,5.230085,"[3.2656520167561607, 1800407.833388641, 125118...","[0.007377214781224138, 8.21190973893998, 364.6...",4.782241e+26
10,"[1.0556273623353377e-306, 9.474935232538201e-3...",860.218196,58.325275,30.377611,"[4.1062984982892665, 1019870.0752583005, 23165...","[0.0016461137253348528, 9.83460930738011, 352....",2.796941e+26
11,"[1.843963468830621e-306, 1.6422868561029073e-3...",1038.338417,27.807431,26.785380,"[3.3164566346722344, 1414587.9685023625, 27990...","[0.00222572941481693, 10.839217565162407, 371....",5.545856e+25
12,"[1.8840484176199853e-306, 1.6772666895043108e-...",1045.590664,28.168301,20.967091,"[3.2476129008880186, 2306571.6899954975, 22943...","[0.013427190075498736, 9.333027784880892, 350....",1.137172e+26
13,"[1.8939230181793106e-306, 1.6858613030920147e-...",1011.062389,27.030637,20.165925,"[3.2408184752665097, 1407774.5779813598, 12450...","[0.0056648680153463075, 6.799702754633871, 345...",2.085945e+26
14,"[1.482066155388237e-306, 1.33518095466835e-306...",391.096230,26.507120,7.682441,"[3.2511459463072914, 1761822.3914941584, 59033...","[0.006826696128782854, 10.287166992733718, 352...",4.458966e+26

In [13]:
df_final.to_parquet('/content/drive/MyDrive/AzONet_New_145/notebooks/3_data_simulation/NewDataAzONetV2/Final_Dataset.parquet')

## Convert the Final DF into Train Test Val in h5

In [14]:
df_final = pd.read_parquet('/content/drive/MyDrive/AzONet_New_145/notebooks/3_data_simulation/NewDataAzONetV2/Final_Dataset.parquet')

In [15]:
x = df_final['Espectro']
n, m = x.shape[0], len(x[0])
x = np.concatenate(x)
x = x.reshape(n, m, 1) # Organizamos la informacion de manera conveniente
x.shape

(1200000, 911, 1)

In [16]:
y = np.array(df_final['Espesor'], dtype = np.float32)
y = y.reshape(-1, 1) # Los datos deben ser de la forma (n, 1)
y.shape

(1200000, 1)

In [17]:
def data_to_TrainTestVal(data:list, folder_path:str, p_train: float = 0.95, p_test: float = 0.04,  )-> None:
    '''
    Description:
        This functions converts a unique h5 file containing all the data into multiples set: train, test y val
        according to the proportions given in the args. It save all the files in a given folder.

    Args:
        file_path (str): Path to the h5 data
        folder_path (str): Folder path where the data will be saved
        p_train (float): Data porcentage to be used for train
        p_test (float): Data porcentage to be used for test

    Returns:
        None
    '''

    x_data = data[0]
    y_data = data[1]

    x_train, y_train = x_data[ : int( x_data.shape[0] * p_train) ], y_data[ : int( y_data.shape[0] * p_train) ]

    x_test, y_test = x_data[int( x_data.shape[0] * p_train) :int( x_data.shape[0] * (p_train + p_test) ) ], y_data[int( y_data.shape[0] * p_train) :int( y_data.shape[0] * (p_train + p_test) ) ]

    x_val, y_val =  x_data[int( x_data.shape[0] * (p_train + p_test) ) : ], y_data[int( y_data.shape[0] * (p_train + p_test) ) : ]

    to_h5(x = x_train, y = y_train, file_name = folder_path + '/train.h5')
    to_h5(x = x_test, y = y_test, file_name = folder_path + '/test.h5')
    to_h5(x = x_val, y = y_val, file_name = folder_path + '/val.h5')

    print('Done!')

In [18]:
def to_h5(x, y, file_name):

    if not os.path.exists(file_name): # Verifica que la ruta no
        print(file_name)
        f = h5py.File(file_name, 'w') # Crea la ruta
        f.create_dataset('x_total', data = x, chunks=True, maxshape=(None, x.shape[1], x.shape[2]) )
        f.create_dataset('y_total', data = y, chunks=True, maxshape=(None, y.shape[1]) )
        print(f.keys())
        f.close()

In [19]:
data_to_TrainTestVal([x, y],
                     folder_path = '/content/drive/MyDrive/AzONet_New_145/notebooks/3_data_simulation/NewDataAzONetV2/Sets', #'/content/drive/MyDrive/AzONet_New_161/notebooks/3_data_simulation/NewDataAzONetV2/Sets',
                     p_train = 0.80,
                     p_test = 0.1)

/content/drive/MyDrive/AzONet_New_145/notebooks/3_data_simulation/NewDataAzONetV2/Sets/train.h5
<KeysViewHDF5 ['x_total', 'y_total']>
/content/drive/MyDrive/AzONet_New_145/notebooks/3_data_simulation/NewDataAzONetV2/Sets/test.h5
<KeysViewHDF5 ['x_total', 'y_total']>
/content/drive/MyDrive/AzONet_New_145/notebooks/3_data_simulation/NewDataAzONetV2/Sets/val.h5
<KeysViewHDF5 ['x_total', 'y_total']>
Done!